export const SCRIPT = '___selva_script'
export const LOG = '___selva_lua_logs'
export const SERVER_HEARTBEAT = '___selva_subscription:server_heartbeat'
export const HEARTBEAT = '___selva_subscription:heartbeat'
export const CLIENTS = '___selva_clients'
export const CACHE = '___selva_cache'
export const REMOVE_SUBSCRIPTION = '___selva_subscription:remove'
export const NEW_SUBSCRIPTION = '___selva_subscription:new'
export const SUBSCRIPTIONS = '___selva_subscriptions'
export const EVENTS = '___selva_events:'
export const SCHEMA_SUBSCRIPTION = '___selva_subscription:schema_update'
export const REGISTRY_UPDATE = '__selva_registry_update'
export const REGISTRY_UPDATE_STATS = '__selva_registry_update_stats'
export const REGISTRY_UPDATE_SUBSCRIPTION =
  '__selva_registry_update_subscriptions'
export const REGISTRY_SUBSCRIPTION_INDEX = '___selva_registry_s_index'
export const SCHEMA = '___selva_schema'
