# Copyright (c) 2012, Ninjaware Oy, Olli Vanhoja <olli.vanhoja@ninjaware.fi>
#
# SPDX-License-Identifier: BSD-2-Clause

# PUnit example project #######################################################

# Add here one or more include directories.
IDIR = ./ ../testable

# Set this to 1 if you will use asserts that compares floats or doubles;
# or 0 disable
PU_LMATH = 1

# Enable Unix Unit (incl. stdin_writer)
PU_UU = 1

# Report oriented mode prints more additional information like test module and
# test case descriptions. 0 = disabled; 1 = enabled.
PU_REPORT_ORIENTED = 1

CFLAGS =

# Location of punit makefile
# Do not touch
include ../punit/Makefile.punit
