export const SCRIPTS: Record<string, string> = {
  // THIS PORTION IS AUTOGENERATED
  /* <BEGIN_INSERT_SCRIPTS */
  'update-schema': 'ff715569760a94b129feb09e2ab6569adf97a426',
  /* <END_INSERT_SCRIPTS */
  // END OF THE AUTOGENERATED PORTION
}

export function getScriptSha(scriptName: string): string | undefined {
  return SCRIPTS[scriptName]
}
