export let SCRIPTS: Record<string, string> = {
  // THIS PORTION IS AUTOGENERATED
  /* <BEGIN_INSERT_SCRIPTS */
  'update-schema': 'b61b3181a99ce7b96792c6b0ff09b1317c797a26',
  /* <END_INSERT_SCRIPTS */
  // END OF THE AUTOGENERATED PORTION
}

export function getScriptSha(scriptName: string): string | undefined {
  return SCRIPTS[scriptName]
}
