export let SCRIPTS: Record<string, string> = {
  // THIS PORTION IS AUTOGENERATED
  /* <BEGIN_INSERT_SCRIPTS */
  'update-schema': '4baff7132a2438592117e5ad63d73b71906f63f8',
  /* <END_INSERT_SCRIPTS */
  // END OF THE AUTOGENERATED PORTION
}

export function getScriptSha(scriptName: string): string | undefined {
  return SCRIPTS[scriptName]
}
