TEST_SRC += test-hierarchy_serialization.c
SRC-hierarchy_serialization += ../redis-alloc.c ../redis-rdb.c ../hierarchy-utils.c ../rpn-mock.c ../subscriptions-mock.c ../errors-mock.c
SRC-hierarchy_serialization += ../../module/alias.c
SRC-hierarchy_serialization += ../../module/errors.c
SRC-hierarchy_serialization += ../../module/hierarchy.c
SRC-hierarchy_serialization += ../../module/selva_node.c
SRC-hierarchy_serialization += ../../module/selva_object.c
SRC-hierarchy_serialization += ../../module/selva_set.c
SRC-hierarchy_serialization += ../../rmutil/sds.c
SRC-hierarchy_serialization += ../../util/cstrings.c
SRC-hierarchy_serialization += ../../util/strnstr.c
SRC-hierarchy_serialization += ../../util/mempool.c
SRC-hierarchy_serialization += ../../util/svector.c
SRC-hierarchy_serialization += ../../util/trx.c
