TEST_SRC += test-hierarchy_deserialization.c
SRC-hierarchy_deserialization += ../redis-alloc.c ../redis-rdb.c ../hierarchy-utils.c ../rpn-mock.c ../subscriptions-mock.c ../errors-mock.c
SRC-hierarchy_deserialization += ../../module/alias.c
SRC-hierarchy_deserialization += ../../module/errors.c
SRC-hierarchy_deserialization += ../../module/hierarchy.c
SRC-hierarchy_deserialization += ../../module/selva_node.c
SRC-hierarchy_deserialization += ../../module/selva_object.c
SRC-hierarchy_deserialization += ../../rmutil/sds.c
SRC-hierarchy_deserialization += ../../util/cstrings.c
SRC-hierarchy_deserialization += ../../util/svector.c
SRC-hierarchy_deserialization += ../../util/trx.c
