TEST_SRC += test-edge.c
SRC-edge += ../redis-alloc.c ../hierarchy-utils.c ../redis-rdb.c ../rpn-mock.c ../subscriptions-mock.c ../errors-mock.c
SRC-edge += ../../module/edge.c
SRC-edge += ../../module/alias.c
SRC-edge += ../../module/hierarchy.c
SRC-edge += ../../module/comparator.c
SRC-edge += ../../module/errors.c
SRC-edge += ../../module/selva_node.c
SRC-edge += ../../module/selva_object.c
SRC-edge += ../../module/selva_set.c
SRC-edge += ../../rmutil/sds.c
SRC-edge += ../../util/cstrings.c
SRC-edge += ../../util/strnstr.c
SRC-edge += ../../util/mempool.c
SRC-edge += ../../util/svector.c
SRC-edge += ../../util/trx.c
