TEST_SRC += test-hierarchy.c
SRC-hierarchy += ../redis-alloc.c ../hierarchy-utils.c ../redis-rdb.c ../rpn-mock.c ../edge-mock.c ../subscriptions-mock.c ../errors-mock.c
SRC-hierarchy += ../../module/alias.c
SRC-hierarchy += ../../module/errors.c
SRC-hierarchy += ../../module/hierarchy.c
SRC-hierarchy += ../../module/selva_node.c
SRC-hierarchy += ../../module/selva_object.c
SRC-hierarchy += ../../module/selva_set.c
SRC-hierarchy += ../../rmutil/sds.c
SRC-hierarchy += ../../util/cstrings.c
SRC-hierarchy += ../../util/strnstr.c
SRC-hierarchy += ../../util/mempool.c
SRC-hierarchy += ../../util/svector.c
SRC-hierarchy += ../../util/trx.c
